<?php
return [
    'download' => 'Download',
    'stamp-report-pdf' => 'StampReportPDF',
    'stamp-cross-check-pdf' => 'StampCrossCheckPDF',
    'forms-report-pdf' => 'FormsLakReportPDF',
    'logistics-client-tag' => 'LogisticsClientTagPDF',
    'order-hp-report-pdf' => 'OrderHPReportPDF',
    'order-hp-report-xls' => 'OrderHPReportXLS',
    'order-hp-report-material-pdf' => 'OrderHPMaterialReportPDF',
    'order-hp-report-lak-pdf' => 'OrderHPLakReportPDF',
    'order-hp-report-lak-pull-pdf' => 'OrderHPLakPullPDF',
    'order-material-pull-pdf' => 'OrderMaterialPullPDF',
    'order-length-stat-pdf' => 'OrderLengthStatPDF',
    'order-hp-prepress-pdf' => 'OrderHPPrepressPDF',
    'order-flexo-report-pdf' => 'OrderFlexoReportPDF',
    'order-flexo-report-sklad-pdf' => 'OrderFlexoSkladReportPDF',
    'order-hp-report-sklad-pdf' => 'OrderFlexoSkladReportPDF',
    'order-hp-print' => 'OrderHPPrint',
    'order-flexo-print' => 'OrderFlexoPrint',
    'storage-inventory-pdf' => 'StorageInventoryPDF',
    'upload-img' => 'UploadImg',
    'tag-print' => 'OrderTagPrint',
    'box-tag-print' => 'OrderBoxTagPrint',
    'qrcode-image' => 'QRCodeImage',
    'barcode-image' => 'BarCodeImage',
    'make-image' => 'MakeImage',
    'storage-material-xls' => 'StorageMaterialXLS',
    'client-tag-print' => 'ClientTagPrint',
    'queues-offset-xls' => 'QueueOffsetReportXLS',
    'sklad-pdf' => 'materialsStoragePDF',
    '404' => 'Page404',
    'form-lak-offset-xml' => 'FormLakOffsetXML',
    'material-pull-history' => 'MaterialPullHistoryPDF',
    'top-clients-pdf' => 'TopClientsPDF',
    'services-report-pdf' => 'ServicesReportPDF',
    'order-print-hp-pdf' => 'OrderPrintHPReportPDF',
];